name: "Full set of tests for PRs and master branch"
on:
  push:
    branches:
      - "master"
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: auto
      - name: Install Nox
        run: |
          uv sync --frozen
          uv pip install nox==2026.04.10
      - name: Run tests
        run: uv run nox --non-interactive --error-on-missing-interpreter --session "tests-${{ matrix.python-version }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: 3.11
          enable-cache: auto
      - name: Install Nox
        run: |
          uv sync --frozen
          uv pip install nox==2026.04.10
      - name: Lint
        run: uv run nox --non-interactive --error-on-missing-interpreter --session "lint"
